### ISSUE TITLE
Add client-go credential plugins

### ISSUE THREAD

**Issue by pmialon** [ca-gip/kubi#39]
The [client-go credential plugin](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins) seems to be the perfect integration for kubi and kubeconfig.

It will be great that kubi support the following output format:
```json
{
  "apiVersion": "client.authentication.k8s.io/v1",
  "kind": "ExecCredential",
  "status": {
    "token": "my-bearer-token"
  }
}
```

this will allow us to configure our kubeconfig this way:
```yaml
users:
- name: user@domain
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1
      command: kubi
      env:
      - name: HTTPS_PROXY
        value: 127.0.0.1:8080
      args:
      - token
      - --kubi-url=kubi.url
      - --username=user@domain
      - --password="xxxxx"
      - --use-proxy
      interactiveMode: IfAvailable
```

The benefit is that the kubi command will be executed by kubectl only when needed.
